import {expect, type Page, test} from '@playwright/test';

enum FieldConsentsUser {
  INDUSTRY_BP = "industry.bp@field-consents.co.uk",
  CASE_OFFICER = "administrator.case.officer@field-consents.co.uk",
  CAM1 = "cam1@field-consents.co.uk"
}

test.describe.configure({ mode: 'parallel' });

async function signIn(page: Page, fieldConsentsUser: FieldConsentsUser) {
  await page.goto('http://localhost:8080/fcs/work-area');
  await page.locator('input[name="g0"]').fill(fieldConsentsUser);
  await page.locator('input[name="g0"]').press('Tab');
  await page.locator('input[name="g1"]').fill("dev1");
  await page.locator('input[name="g1"]').press('Enter');
}

async function assignToCamUser(page: Page, reference: string) {
  await page.getByRole('tab', { name: 'Unassigned' }).click();
  await page.getByRole('link', { name: reference }).click();
  await page.getByRole('button', { name: 'Take ownership' }).click();
  await page.getByRole('link', { name: 'Consent preparation' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Assign to CAM' }).click();
  await page.getByRole('textbox', { name: 'Select one...' }).click();
  await page.getByRole('option', { name: 'CAM 1' }).click();
  await page.getByRole('button', { name: 'Assign CAM' }).click();
}

test('submit flare application', async ({ page }) => {
  await signIn(page, FieldConsentsUser.INDUSTRY_BP);
  
  await page.getByRole('link', { name: 'Manage fields/facilities' }).click();
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('searchbox').fill('FARRAGON');
  await page.getByRole('option', { name: 'FARRAGON' }).click();
  await page.getByRole('button', { name: 'Manage field/facility' }).click();
  await page.getByRole('button', { name: 'Start application' }).click();
  await page.getByLabel('Flare').check();
  await page.getByLabel('Production').check();
  await page.getByLabel('Flare').check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Save and continue' }).click();
  await page.getByRole('link', { name: 'Application rationale' }).click();
  await page.getByLabel('Increase', { exact: true }).check();
  await page.getByLabel('Explain why you are').click();
  await page.getByLabel('Explain why you are').fill('application rationale increase reason');
  await page.getByRole('group', { name: 'Where does the flaring take' }).getByRole('combobox').click();
  await page.getByRole('searchbox').click();
  await page.getByRole('searchbox').fill('FARRAGON');
  await page.getByRole('option', { name: 'FARRAGON' }).click();
  await page.getByRole('group', { name: 'What is the host?' }).getByRole('combobox').click();
  await page.getByRole('searchbox').fill('FARRAGON');
  await page.getByRole('option', { name: 'FARRAGON' }).click();
  await page.getByRole('button', { name: 'Save and continue' }).click();
  await page.getByRole('link', { name: 'Consent duration' }).click();
  await page.getByLabel('Annual consent').check();
  await page.getByLabel('2025').check();
  await page.getByRole('button', { name: 'Save and complete' }).click();
  await page.getByRole('link', { name: 'Additional fields and licences' }).click();
  await page.getByLabel('No').check();
  await page.getByRole('button', { name: 'Save and continue' }).click();
  await page.getByRole('link', { name: 'Flare system(s)' }).click();
  await page.getByLabel('HP flare system').check();
  await page.getByLabel('Description').click();
  await page.getByLabel('Description').fill('high pressure flare system description');
  await page.getByLabel('Yes').check();
  await page.getByRole('button', { name: 'Save and continue' }).click();
  await page.getByLabel('No').check();
  await page.getByRole('button', { name: 'Save and continue' }).click();
  await page.getByRole('link', { name: 'Flare report' }).click();
  await page.getByLabel('2024').check();
  await page.getByLabel('Which is the latest full').selectOption('JULY');
  await page.getByRole('button', { name: 'Save and continue' }).click();
  await page.getByRole('row', { name: 'Aug 2023   Category A' }).getByLabel('Category A').click();
  await page.getByRole('row', { name: 'Aug 2023   Category A' }).getByLabel('Category A').fill('1');
  await page.getByRole('row', { name: 'Aug 2023   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Aug 2023   Category A   1' }).getByLabel('Category B').fill('1');
  await page.getByRole('row', { name: 'Aug 2023   Category A   1' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Aug 2023   Category A   1' }).getByLabel('Category C').fill('1');
  await page.getByRole('row', { name: 'Aug 2023   Category A   1' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Aug 2023   Category A   1' }).getByLabel('days of total shutdown').fill('1');
  await page.getByRole('row', { name: 'Aug 2023   Category A   1' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Aug 2023   Category A   1' }).getByLabel('comments').fill('1');
  await page.getByRole('row', { name: 'Aug 2023   Category A   1' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Sep 2023   Category A' }).getByLabel('Category A').fill('1');
  await page.getByRole('row', { name: 'Sep 2023   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Sep 2023   Category A   1' }).getByLabel('Category B').fill('1');
  await page.getByRole('row', { name: 'Sep 2023   Category A   1' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Sep 2023   Category A   1' }).getByLabel('Category C').fill('1');
  await page.getByRole('row', { name: 'Sep 2023   Category A   1' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Sep 2023   Category A   1' }).getByLabel('days of total shutdown').fill('1');
  await page.getByRole('row', { name: 'Sep 2023   Category A   1' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Sep 2023   Category A   1' }).getByLabel('comments').fill('1');
  await page.getByRole('row', { name: 'Sep 2023   Category A   1' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Oct 2023   Category A' }).getByLabel('Category A').fill('1');
  await page.getByRole('row', { name: 'Oct 2023   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Oct 2023   Category A   1' }).getByLabel('Category B').fill('1');
  await page.getByRole('row', { name: 'Oct 2023   Category A   1' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Oct 2023   Category A   1' }).getByLabel('Category C').fill('1');
  await page.getByRole('row', { name: 'Oct 2023   Category A   1' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Oct 2023   Category A   1' }).getByLabel('days of total shutdown').fill('1');
  await page.getByRole('row', { name: 'Oct 2023   Category A   1' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Oct 2023   Category A   1' }).getByLabel('comments').fill('1');
  await page.getByRole('row', { name: 'Oct 2023   Category A   1' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Nov 2023   Category A' }).getByLabel('Category A').fill('1');
  await page.getByRole('row', { name: 'Nov 2023   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Nov 2023   Category A   1' }).getByLabel('Category B').fill('1');
  await page.getByRole('row', { name: 'Nov 2023   Category A   1' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Nov 2023   Category A   1' }).getByLabel('Category C').fill('1');
  await page.getByRole('row', { name: 'Nov 2023   Category A   1' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Nov 2023   Category A   1' }).getByLabel('days of total shutdown').fill('1');
  await page.getByRole('row', { name: 'Nov 2023   Category A   1' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Nov 2023   Category A   1' }).getByLabel('comments').fill('1');
  await page.getByRole('row', { name: 'Nov 2023   Category A   1' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Dec 2023   Category A' }).getByLabel('Category A').fill('1');
  await page.getByRole('row', { name: 'Dec 2023   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Dec 2023   Category A   1' }).getByLabel('Category B').fill('1');
  await page.getByRole('row', { name: 'Dec 2023   Category A   1' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Dec 2023   Category A   1' }).getByLabel('Category C').fill('1');
  await page.getByRole('row', { name: 'Dec 2023   Category A   1' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Dec 2023   Category A   1' }).getByLabel('days of total shutdown').fill('1');
  await page.getByRole('row', { name: 'Dec 2023   Category A   1' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Dec 2023   Category A   1' }).getByLabel('comments').fill('1');
  await page.getByRole('row', { name: 'Dec 2023   Category A   1' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Jan 2024   Category A' }).getByLabel('Category A').fill('1');
  await page.getByRole('row', { name: 'Jan 2024   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Jan 2024   Category A   1' }).getByLabel('Category B').fill('1');
  await page.getByRole('row', { name: 'Jan 2024   Category A   1' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Jan 2024   Category A   1' }).getByLabel('Category C').fill('1');
  await page.getByRole('row', { name: 'Jan 2024   Category A   1' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Jan 2024   Category A   1' }).getByLabel('days of total shutdown').fill('1');
  await page.getByRole('row', { name: 'Jan 2024   Category A   1' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Jan 2024   Category A   1' }).getByLabel('comments').fill('1');
  await page.getByRole('row', { name: 'Jan 2024   Category A   1' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Feb 2024   Category A' }).getByLabel('Category A').fill('1');
  await page.getByRole('row', { name: 'Feb 2024   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Feb 2024   Category A   1' }).getByLabel('Category B').fill('1');
  await page.getByRole('row', { name: 'Feb 2024   Category A   1' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Feb 2024   Category A   1' }).getByLabel('Category C').fill('1');
  await page.getByRole('row', { name: 'Feb 2024   Category A   1' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Feb 2024   Category A   1' }).getByLabel('days of total shutdown').fill('1');
  await page.getByRole('row', { name: 'Feb 2024   Category A   1' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Feb 2024   Category A   1' }).getByLabel('comments').fill('1');
  await page.getByRole('row', { name: 'Feb 2024   Category A   1' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Mar 2024   Category A' }).getByLabel('Category A').fill('1');
  await page.getByRole('row', { name: 'Mar 2024   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Mar 2024   Category A   1' }).getByLabel('Category B').fill('1');
  await page.getByRole('row', { name: 'Mar 2024   Category A   1' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Mar 2024   Category A   1' }).getByLabel('Category C').fill('1');
  await page.getByRole('row', { name: 'Mar 2024   Category A   1' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Mar 2024   Category A   1' }).getByLabel('days of total shutdown').fill('1');
  await page.getByRole('row', { name: 'Mar 2024   Category A   1' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Mar 2024   Category A   1' }).getByLabel('comments').fill('1');
  await page.getByRole('row', { name: 'Mar 2024   Category A   1' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Apr 2024   Category A' }).getByLabel('Category A').fill('1');
  await page.getByRole('row', { name: 'Apr 2024   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Apr 2024   Category A   1' }).getByLabel('Category B').fill('1');
  await page.getByRole('row', { name: 'Apr 2024   Category A   1' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Apr 2024   Category A   1' }).getByLabel('Category C').fill('1');
  await page.getByRole('row', { name: 'Apr 2024   Category A   1' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Apr 2024   Category A   1' }).getByLabel('days of total shutdown').fill('1');
  await page.getByRole('row', { name: 'Apr 2024   Category A   1' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Apr 2024   Category A   1' }).getByLabel('comments').fill('1');
  await page.getByRole('row', { name: 'Apr 2024   Category A   1' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'May 2024   Category A' }).getByLabel('Category A').fill('1');
  await page.getByRole('row', { name: 'May 2024   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'May 2024   Category A   1' }).getByLabel('Category B').fill('1');
  await page.getByRole('row', { name: 'May 2024   Category A   1' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'May 2024   Category A   1' }).getByLabel('Category C').fill('1');
  await page.getByRole('row', { name: 'May 2024   Category A   1' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'May 2024   Category A   1' }).getByLabel('days of total shutdown').fill('1');
  await page.getByRole('row', { name: 'May 2024   Category A   1' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'May 2024   Category A   1' }).getByLabel('comments').fill('1');
  await page.getByRole('row', { name: 'May 2024   Category A   1' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Jun 2024   Category A' }).getByLabel('Category A').fill('1');
  await page.getByRole('row', { name: 'Jun 2024   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Jun 2024   Category A   1' }).getByLabel('Category B').fill('1');
  await page.getByRole('row', { name: 'Jun 2024   Category A   1' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Jun 2024   Category A   1' }).getByLabel('Category C').fill('1');
  await page.getByRole('row', { name: 'Jun 2024   Category A   1' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Jun 2024   Category A   1' }).getByLabel('days of total shutdown').fill('1');
  await page.getByRole('row', { name: 'Jun 2024   Category A   1' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Jun 2024   Category A   1' }).getByLabel('comments').fill('1');
  await page.getByRole('row', { name: 'Jun 2024   Category A   1' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Jul 2024   Category A' }).getByLabel('Category A').fill('1');
  await page.getByRole('row', { name: 'Jul 2024   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Jul 2024   Category A   1' }).getByLabel('Category B').fill('1');
  await page.getByRole('row', { name: 'Jul 2024   Category A   1' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Jul 2024   Category A   1' }).getByLabel('Category C').fill('1');
  await page.getByRole('row', { name: 'Jul 2024   Category A   1' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Jul 2024   Category A   1' }).getByLabel('days of total shutdown').fill('1');
  await page.getByRole('row', { name: 'Jul 2024   Category A   1' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Jul 2024   Category A   1' }).getByLabel('comments').fill('1');
  await page.getByRole('button', { name: 'Save and continue' }).click();
  await page.getByRole('link', { name: 'Flare report gas properties' }).click();
  await page.getByLabel('Category A standard density').click();
  await page.getByLabel('Category A standard density').fill('50');
  await page.getByLabel('Category A standard density').press('Tab');
  await page.getByLabel('Category B standard density').fill('50');
  await page.getByLabel('Category B standard density').press('Tab');
  await page.getByLabel('Category C standard density').fill('50');
  await page.getByLabel('Category C standard density').press('Tab');
  await page.getByLabel('Category A inert gas content').fill('50');
  await page.getByLabel('Category A inert gas content').press('Tab');
  await page.getByLabel('Category B inert gas content').fill('50');
  await page.getByLabel('Category B inert gas content').press('Tab');
  await page.getByLabel('Category C inert gas content').fill('50');
  await page.getByLabel('Category C inert gas content').press('Tab');
  await page.getByLabel('Category A hydrocarbon content').fill('50');
  await page.getByLabel('Category A hydrocarbon content').press('Tab');
  await page.getByLabel('Category B hydrocarbon content').fill('50');
  await page.getByLabel('Category B hydrocarbon content').press('Tab');
  await page.getByLabel('Category C hydrocarbon content').fill('50');
  await page.getByLabel('Category C hydrocarbon content').press('Tab');
  await page.getByLabel('Yes').check();
  await page.getByRole('button', { name: 'Save and continue' }).click();
  await page.getByRole('link', { name: 'Annual consent' }).click();
  await page.getByRole('row', { name: 'Jan 2025   Category A' }).getByLabel('Category A').click();
  await page.getByRole('row', { name: 'Jan 2025   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Jan 2025   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Jan 2025   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Jan 2025   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Jan 2025   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('cell', { name: 'Category C   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Jan 2025   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Jan 2025   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Feb 2025   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Feb 2025   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Feb 2025   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Feb 2025   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Feb 2025   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Feb 2025   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Feb 2025   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Feb 2025   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Mar 2025   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Mar 2025   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Mar 2025   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Mar 2025   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Mar 2025   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Mar 2025   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Mar 2025   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Mar 2025   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Apr 2025   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Apr 2025   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Apr 2025   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Apr 2025   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Apr 2025   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Apr 2025   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Apr 2025   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Apr 2025   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'May 2025   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'May 2025   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'May 2025   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'May 2025   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'May 2025   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'May 2025   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'May 2025   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'May 2025   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Jun 2025   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Jun 2025   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Jun 2025   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Jun 2025   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Jun 2025   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Jun 2025   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Jun 2025   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Jun 2025   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Jul 2025   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Jul 2025   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Jul 2025   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Jul 2025   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Jul 2025   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Jul 2025   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Jul 2025   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Jul 2025   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Aug 2025   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Aug 2025   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Aug 2025   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Aug 2025   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Aug 2025   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Aug 2025   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Aug 2025   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Aug 2025   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Sep 2025   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Sep 2025   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Sep 2025   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Sep 2025   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Sep 2025   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Sep 2025   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Sep 2025   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Sep 2025   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Oct 2025   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Oct 2025   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Oct 2025   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Oct 2025   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Oct 2025   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Oct 2025   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Oct 2025   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Oct 2025   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Nov 2025   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Nov 2025   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Nov 2025   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Nov 2025   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Nov 2025   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Nov 2025   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Nov 2025   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Nov 2025   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Dec 2025   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Dec 2025   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Dec 2025   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Dec 2025   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Dec 2025   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Dec 2025   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Dec 2025   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('button', { name: 'Save and continue' }).click();
  await page.getByRole('link', { name: 'Supporting information' }).click();
  await page.getByLabel('Notes').click();
  await page.getByLabel('Notes').fill('supporting information notes');
  await page.getByLabel('ERAP alignment studies and').click();
  await page.getByLabel('ERAP alignment studies and').fill('supporting information erap alignment studies and projects');
  await page.getByRole('button', { name: 'Save and continue' }).click();
  await page.getByRole('link', { name: 'Review and submit' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByRole('heading', { name: 'Application submitted' })).toBeVisible();
  const reference = await page.getByText('FCON').innerText();

  await page.getByRole('button', { name: 'Sign out' }).click();

  await signIn(page, FieldConsentsUser.CASE_OFFICER);
  await assignToCamUser(page, reference);

  await page.getByRole('button', { name: 'Sign out' }).click();

  await signIn(page, FieldConsentsUser.CAM1);
  await page.getByRole('link', { name: reference }).click();
  await page.getByRole('link', { name: 'Consent issuing' }).click();
  await page.getByRole('button', { name: 'Ready to grant and issue' }).click();
});

test('submit vent application', async ({ page }) => {
  await signIn(page, FieldConsentsUser.INDUSTRY_BP)

  await page.getByRole('link', { name: 'Manage fields/facilities' }).click();
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('searchbox').fill('FARRAGON');
  await page.getByRole('option', { name: 'FARRAGON' }).click();
  await page.getByRole('button', { name: 'Manage field/facility' }).click();
  await page.getByRole('button', { name: 'Start application' }).click();
  await page.getByLabel('Vent').check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Save and continue' }).click();

  await page.getByRole('link', { name: 'Application rationale' }).click();
  await page.getByLabel('Decrease').check();
  await page.getByRole('group', { name: 'Where does the venting take' }).getByRole('combobox').click();
  await page.getByRole('searchbox').fill('FARRAGON');
  await page.getByRole('option', { name: 'FARRAGON' }).click();
  await page.getByRole('group', { name: 'What is the host?' }).getByRole('combobox').click();
  await page.getByRole('searchbox').fill('FARRAGON');
  await page.getByRole('option', { name: 'FARRAGON' }).click();
  await page.getByRole('button', { name: 'Save and continue' }).click();

  await page.getByRole('link', { name: 'Consent duration' }).click();
  await page.getByLabel('Short term consent').check();
  await page.getByRole('group', { name: 'Start date' }).getByLabel('Day').click();
  await page.getByRole('group', { name: 'Start date' }).getByLabel('Day').fill('1');
  await page.getByRole('group', { name: 'Start date' }).getByLabel('Day').press('Tab');
  await page.getByRole('group', { name: 'Start date' }).getByLabel('Month').fill('1');
  await page.getByRole('group', { name: 'Start date' }).getByLabel('Month').press('Tab');
  await page.getByRole('group', { name: 'Start date' }).getByLabel('Year').fill('2025');
  await page.getByRole('group', { name: 'Start date' }).getByLabel('Year').press('Tab');
  await page.getByRole('group', { name: 'End date' }).getByLabel('Day').fill('31');
  await page.getByRole('group', { name: 'End date' }).getByLabel('Day').press('Tab');
  await page.getByRole('group', { name: 'End date' }).getByLabel('Month').fill('3');
  await page.getByRole('group', { name: 'End date' }).getByLabel('Month').press('Tab');
  await page.getByRole('group', { name: 'End date' }).getByLabel('Year').fill('2025');
  await page.getByRole('button', { name: 'Save and complete' }).click();

  await page.getByRole('link', { name: 'Additional fields and licences' }).click();
  await page.getByLabel('No').check();
  await page.getByRole('button', { name: 'Save and continue' }).click();

  await page.getByRole('link', { name: 'Vent system(s)' }).click();
  await page.getByLabel('HP vent system').check();
  await page.getByLabel('Description').click();
  await page.getByLabel('Description').fill('hp vent system comment');
  await page.getByLabel('Yes').check();
  await page.getByRole('button', { name: 'Save and continue' }).click();
  await page.getByLabel('Yes').check();
  await page.getByRole('button', { name: 'Save and continue' }).click();

  await page.getByRole('link', { name: 'Vent report' }).click();
  await page.getByLabel('2024').check();
  await page.getByLabel('Which is the latest full').selectOption('JULY');
  await page.getByRole('button', { name: 'Save and continue' }).click();
  await page.getByRole('row', { name: 'Aug 2023   Category A' }).getByLabel('Category A').click();
  await page.getByRole('row', { name: 'Aug 2023   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Aug 2023   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Aug 2023   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Aug 2023   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Aug 2023   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Aug 2023   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Aug 2023   Category A   5' }).getByLabel('days of total shutdown').fill('5');
  await page.getByRole('row', { name: 'Aug 2023   Category A   5' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Aug 2023   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Aug 2023   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Sep 2023   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Sep 2023   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Sep 2023   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Sep 2023   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Sep 2023   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Sep 2023   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Sep 2023   Category A   5' }).getByLabel('days of total shutdown').fill('5');
  await page.getByRole('row', { name: 'Sep 2023   Category A   5' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Sep 2023   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Sep 2023   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Oct 2023   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Oct 2023   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Oct 2023   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Oct 2023   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Oct 2023   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Oct 2023   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Oct 2023   Category A   5' }).getByLabel('days of total shutdown').fill('5');
  await page.getByRole('row', { name: 'Oct 2023   Category A   5' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Oct 2023   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Oct 2023   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Nov 2023   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Nov 2023   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Nov 2023   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Nov 2023   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Nov 2023   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Nov 2023   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Nov 2023   Category A   5' }).getByLabel('days of total shutdown').fill('5');
  await page.getByRole('row', { name: 'Nov 2023   Category A   5' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Nov 2023   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Nov 2023   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Dec 2023   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Dec 2023   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Dec 2023   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Dec 2023   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Dec 2023   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Dec 2023   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Dec 2023   Category A   5' }).getByLabel('days of total shutdown').fill('5');
  await page.getByRole('row', { name: 'Dec 2023   Category A   5' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Dec 2023   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Dec 2023   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Jan 2024   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Jan 2024   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Jan 2024   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Jan 2024   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Jan 2024   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Jan 2024   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Jan 2024   Category A   5' }).getByLabel('days of total shutdown').fill('5');
  await page.getByRole('row', { name: 'Jan 2024   Category A   5' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Jan 2024   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Jan 2024   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Feb 2024   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Feb 2024   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Feb 2024   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Feb 2024   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Feb 2024   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Feb 2024   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Feb 2024   Category A   5' }).getByLabel('days of total shutdown').fill('5');
  await page.getByRole('row', { name: 'Feb 2024   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Feb 2024   Category A   5' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Feb 2024   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Mar 2024   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Mar 2024   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Mar 2024   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Mar 2024   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Mar 2024   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Mar 2024   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Mar 2024   Category A   5' }).getByLabel('days of total shutdown').fill('5');
  await page.getByRole('row', { name: 'Mar 2024   Category A   5' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Mar 2024   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Mar 2024   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Apr 2024   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Apr 2024   Category A   5' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Apr 2024   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Apr 2024   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Apr 2024   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Apr 2024   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Apr 2024   Category A   5' }).getByLabel('days of total shutdown').fill('5');
  await page.getByRole('row', { name: 'Apr 2024   Category A   5' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Apr 2024   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Apr 2024   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'May 2024   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'May 2024   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'May 2024   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'May 2024   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'May 2024   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'May 2024   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'May 2024   Category A   5' }).getByLabel('days of total shutdown').fill('5');
  await page.getByRole('row', { name: 'May 2024   Category A   5' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'May 2024   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'May 2024   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Jun 2024   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Jun 2024   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Jun 2024   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Jun 2024   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Jun 2024   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Jun 2024   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Jun 2024   Category A   5' }).getByLabel('days of total shutdown').fill('5');
  await page.getByRole('row', { name: 'Jun 2024   Category A   5' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Jun 2024   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('row', { name: 'Jun 2024   Category A   5' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Jul 2024   Category A' }).getByLabel('Category A').fill('5');
  await page.getByRole('row', { name: 'Jul 2024   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Jul 2024   Category A   5' }).getByLabel('Category B').fill('5');
  await page.getByRole('row', { name: 'Jul 2024   Category A   5' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Jul 2024   Category A   5' }).getByLabel('Category C').fill('5');
  await page.getByRole('row', { name: 'Jul 2024   Category A   5' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Jul 2024   Category A   5' }).getByLabel('days of total shutdown').fill('5');
  await page.getByRole('row', { name: 'Jul 2024   Category A   5' }).getByLabel('days of total shutdown').press('Tab');
  await page.getByRole('row', { name: 'Jul 2024   Category A   5' }).getByLabel('comments').fill('5');
  await page.getByRole('button', { name: 'Save and continue' }).click();

  await page.getByRole('link', { name: 'Vent report gas properties' }).click();
  await page.getByLabel('Category A standard density').click();
  await page.getByLabel('Category A standard density').fill('50');
  await page.getByLabel('Category A standard density').press('Tab');
  await page.getByLabel('Category B standard density').fill('50');
  await page.getByLabel('Category B standard density').press('Tab');
  await page.getByLabel('Category C standard density').fill('50');
  await page.getByLabel('Category C standard density').press('Tab');
  await page.getByLabel('Category A inert gas content').fill('50');
  await page.getByLabel('Category A inert gas content').press('Tab');
  await page.getByLabel('Category B inert gas content').fill('50');
  await page.getByLabel('Category B inert gas content').press('Tab');
  await page.getByLabel('Category C inert gas content').fill('50');
  await page.getByLabel('Category C inert gas content').press('Tab');
  await page.getByLabel('Category A hydrocarbon content').fill('50');
  await page.getByLabel('Category A hydrocarbon content').press('Tab');
  await page.getByLabel('Category B hydrocarbon content').fill('50');
  await page.getByLabel('Category B hydrocarbon content').press('Tab');
  await page.getByLabel('Category C hydrocarbon content').fill('50');
  await page.getByLabel('Yes').check();
  await page.getByRole('button', { name: 'Save and continue' }).click();

  await page.getByRole('link', { name: 'Short term consent' }).click();
  await page.getByRole('row', { name: 'Jan 2025 31   Category A' }).getByLabel('Category A').click();
  await page.getByRole('row', { name: 'Jan 2025 31   Category A' }).getByLabel('Category A').fill('10');
  await page.getByRole('row', { name: 'Jan 2025 31   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Jan 2025 31   Category A   10' }).getByLabel('Category B').fill('10');
  await page.getByRole('row', { name: 'Jan 2025 31   Category A   10' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Jan 2025 31   Category A   10' }).getByLabel('Category C').fill('10');
  await page.getByRole('row', { name: 'Jan 2025 31   Category A   10' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Jan 2025 31   Category A   10' }).getByLabel('comments').fill('test');
  await page.getByRole('row', { name: 'Jan 2025 31   Category A   10' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Feb 2025 28   Category A' }).getByLabel('Category A').fill('10');
  await page.getByRole('row', { name: 'Feb 2025 28   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Feb 2025 28   Category A   10' }).getByLabel('Category B').fill('10');
  await page.getByRole('row', { name: 'Feb 2025 28   Category A   10' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Feb 2025 28   Category A   10' }).getByLabel('Category C').fill('10');
  await page.getByRole('row', { name: 'Feb 2025 28   Category A   10' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Feb 2025 28   Category A   10' }).getByLabel('comments').fill('test 2');
  await page.getByRole('row', { name: 'Feb 2025 28   Category A   10' }).getByLabel('comments').press('Tab');
  await page.getByRole('row', { name: 'Mar 2025 31   Category A' }).getByLabel('Category A').fill('10');
  await page.getByRole('row', { name: 'Mar 2025 31   Category A' }).getByLabel('Category A').press('Tab');
  await page.getByRole('row', { name: 'Mar 2025 31   Category A   10' }).getByLabel('Category B').fill('10');
  await page.getByRole('row', { name: 'Mar 2025 31   Category A   10' }).getByLabel('Category B').press('Tab');
  await page.getByRole('row', { name: 'Mar 2025 31   Category A   10' }).getByLabel('Category C').fill('10');
  await page.getByRole('row', { name: 'Mar 2025 31   Category A   10' }).getByLabel('Category C').press('Tab');
  await page.getByRole('row', { name: 'Mar 2025 31   Category A   10' }).getByLabel('comments').fill('test 3');
  await page.getByRole('button', { name: 'Save and continue' }).click();

  await page.getByRole('link', { name: 'Supporting information' }).click();
  await page.getByLabel('Notes').click();
  await page.getByLabel('Notes').fill('test');
  await page.getByLabel('ERAP alignment studies and').click();
  await page.getByLabel('ERAP alignment studies and').fill('test');
  await page.getByRole('button', { name: 'Save and continue' }).click();

  await page.getByRole('link', { name: 'Review and submit' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page.getByRole('heading', { name: 'Application submitted' })).toBeVisible();
  const reference = await page.getByText('VCON').innerText();

  await page.getByRole('button', { name: 'Sign out' }).click();

  await signIn(page, FieldConsentsUser.CASE_OFFICER);
  await assignToCamUser(page, reference);

  await page.getByRole('button', { name: 'Sign out' }).click();

  await signIn(page, FieldConsentsUser.CAM1)
  await page.getByRole('link', { name: reference }).click();
  await page.getByRole('link', { name: 'Consent issuing' }).click();
  await page.getByRole('button', { name: 'Ready to grant and issue' }).click();
});

test('submit production application', async ({ page }) => {
  await signIn(page, FieldConsentsUser.INDUSTRY_BP);

  await page.getByRole('link', { name: 'Manage fields/facilities' }).click();
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('searchbox').fill('NEPTUNE');
  await page.getByRole('option', { name: 'NEPTUNE' }).click();
  await page.getByRole('button', { name: 'Manage field/facility' }).click();
  await page.getByRole('button', { name: 'Start application' }).click();
  await page.getByLabel('Production').check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Save and continue' }).click();

  await page.getByRole('link', { name: 'Application rationale' }).click();
  await page.getByLabel('Decrease').check();
  await page.getByRole('group', { name: 'At which location are the' }).getByRole('combobox').click();
  await page.getByRole('searchbox').fill('NEPT');
  await page.getByRole('option', { name: 'NEPTUNE' }).click();
  await page.getByRole('group', { name: 'What is the host?' }).getByRole('combobox').click();
  await page.getByRole('searchbox').fill('NEP');
  await page.getByRole('option', { name: 'NEPTUNE' }).click();
  await page.getByRole('button', { name: 'Save and continue' }).click();

  await page.getByRole('link', { name: 'Consent duration' }).click();
  await page.getByLabel('Annual consent').check();
  await page.getByLabel('2026').check();
  await page.getByRole('button', { name: 'Save and complete' }).click();

  await page.getByRole('link', { name: 'Gas injection' }).click();
  await page.getByLabel('No').check();
  await page.getByRole('button', { name: 'Save and continue' }).click();

  await page.getByRole('link', { name: 'Annual consent' }).click();
  await page.getByLabel('Oil min value January').click();
  await page.getByLabel('Oil min value January').fill('9');
  await page.getByLabel('Oil min value January').press('Tab');
  await page.getByLabel('Oil max value January').fill('9');
  await page.getByLabel('Oil max value January').press('Tab');
  await page.getByLabel('Gas min value January').fill('9');
  await page.getByLabel('Gas min value January').press('Tab');
  await page.getByLabel('Gas max value January').fill('9');
  await page.getByLabel('Gas max value January').press('Tab');
  await page.getByLabel('Oil min value February').fill('9');
  await page.getByLabel('Oil min value February').press('Tab');
  await page.getByLabel('Oil max value February').fill('9');
  await page.getByLabel('Oil max value February').press('Tab');
  await page.getByLabel('Gas min value February').fill('9');
  await page.getByLabel('Gas min value February').press('Tab');
  await page.getByLabel('Gas max value February').fill('9');
  await page.getByLabel('Gas max value February').press('Tab');
  await page.getByLabel('Oil min value March').fill('9');
  await page.getByLabel('Oil min value March').press('Tab');
  await page.getByLabel('Oil max value March').fill('9');
  await page.getByLabel('Oil max value March').press('Tab');
  await page.getByLabel('Gas min value March').fill('9');
  await page.getByLabel('Gas min value March').press('Tab');
  await page.getByLabel('Gas max value March').fill('9');
  await page.getByLabel('Gas max value March').press('Tab');
  await page.getByLabel('Oil min value April').fill('9');
  await page.getByLabel('Oil min value April').press('Tab');
  await page.getByLabel('Oil max value April').fill('9');
  await page.getByLabel('Oil max value April').press('Tab');
  await page.getByLabel('Gas min value April').fill('9');
  await page.getByLabel('Gas min value April').press('Tab');
  await page.getByLabel('Gas max value April').fill('9');
  await page.getByLabel('Gas max value April').press('Tab');
  await page.getByLabel('Oil min value May').fill('9');
  await page.getByLabel('Oil min value May').press('Tab');
  await page.getByLabel('Oil max value May').fill('9');
  await page.getByLabel('Oil max value May').press('Tab');
  await page.getByLabel('Gas min value May').fill('9');
  await page.getByLabel('Gas min value May').press('Tab');
  await page.getByLabel('Gas max value May').fill('9');
  await page.getByLabel('Gas max value May').press('Tab');
  await page.getByLabel('Oil min value June').fill('9');
  await page.getByLabel('Oil min value June').press('Tab');
  await page.getByLabel('Oil max value June').fill('9');
  await page.getByLabel('Oil max value June').press('Tab');
  await page.getByLabel('Gas min value June').fill('9');
  await page.getByLabel('Gas min value June').press('Tab');
  await page.getByLabel('Gas max value June').fill('9');
  await page.getByLabel('Gas max value June').press('Tab');
  await page.getByLabel('Oil min value July').fill('9');
  await page.getByLabel('Oil min value July').press('Tab');
  await page.getByLabel('Oil max value July').fill('9');
  await page.getByLabel('Oil max value July').press('Tab');
  await page.getByLabel('Gas min value July').fill('9');
  await page.getByLabel('Gas min value July').press('Tab');
  await page.getByLabel('Gas max value July').fill('9');
  await page.getByLabel('Gas max value July').press('Tab');
  await page.getByLabel('Oil min value August').fill('9');
  await page.getByLabel('Oil min value August').press('Tab');
  await page.getByLabel('Oil max value August').fill('9');
  await page.getByLabel('Oil max value August').press('Tab');
  await page.getByLabel('Gas min value August').fill('9');
  await page.getByLabel('Gas min value August').press('Tab');
  await page.getByLabel('Gas max value August').fill('9');
  await page.getByLabel('Gas max value August').press('Tab');
  await page.getByLabel('Oil min value September').fill('9');
  await page.getByLabel('Oil min value September').press('Tab');
  await page.getByLabel('Oil max value September').fill('9');
  await page.getByLabel('Oil max value September').press('Tab');
  await page.getByLabel('Gas min value September').fill('9');
  await page.getByLabel('Gas min value September').press('Tab');
  await page.getByLabel('Gas max value September').fill('9');
  await page.getByLabel('Gas max value September').press('Tab');
  await page.getByLabel('Oil min value October').fill('9');
  await page.getByLabel('Oil min value October').press('Tab');
  await page.getByLabel('Oil max value October').fill('9');
  await page.getByLabel('Oil max value October').press('Tab');
  await page.getByLabel('Gas min value October').fill('9');
  await page.getByLabel('Gas min value October').press('Tab');
  await page.getByLabel('Gas max value October').fill('9');
  await page.getByLabel('Gas max value October').press('Tab');
  await page.getByLabel('Oil min value November').fill('9');
  await page.getByLabel('Oil min value November').press('Tab');
  await page.getByLabel('Oil max value November').fill('9');
  await page.getByLabel('Oil max value November').press('Tab');
  await page.getByLabel('Gas min value November').fill('9');
  await page.getByLabel('Gas min value November').press('Tab');
  await page.getByLabel('Gas max value November').fill('9');
  await page.getByLabel('Gas max value November').press('Tab');
  await page.getByLabel('Oil min value December').fill('9');
  await page.getByLabel('Oil min value December').press('Tab');
  await page.getByLabel('Oil max value December').fill('9');
  await page.getByLabel('Oil max value December').press('Tab');
  await page.getByLabel('Gas min value December').fill('9');
  await page.getByLabel('Gas min value December').press('Tab');
  await page.getByLabel('Gas max value December').fill('9');
  await page.getByRole('button', { name: 'Save and continue' }).click();
  
  await page.getByRole('link', { name: 'EIA screening direction' }).click();
  await page.getByLabel('No').check();
  await page.getByRole('button', { name: 'Save and continue' }).click();
  
  await page.getByRole('link', { name: 'Supporting information' }).click();
  await page.getByLabel('Notes').click();
  await page.getByLabel('Notes').fill('test');
  await page.getByRole('button', { name: 'Save and continue' }).click();

  await page.getByRole('link', { name: 'Review and submit' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  const reference = await page.getByText('PCON').innerText();

  await page.getByRole('button', { name: 'Sign out' }).click();

  await signIn(page, FieldConsentsUser.CASE_OFFICER);;
  await assignToCamUser(page, reference);

  await page.getByRole('button', { name: 'Sign out' }).click();

  await signIn(page, FieldConsentsUser.CAM1);
  await page.getByRole('link', { name: reference }).click();
  await page.getByRole('link', { name: 'Consent issuing' }).click();
  await page.getByRole('button', { name: 'Ready to grant and issue' }).click();
});