server.error.path=/error
server.error.whitelabel.enabled=false
server.servlet.context-path=${FCS_CONTEXT_PATH:/fcs}

# Branding
branding.service.name=Field Consents
branding.service.mnemonic=FCS
branding.customer.name=North Sea Transition Authority
branding.customer.mnemonic=NSTA
branding.customer.email=consents@nstauthority.co.uk
branding.customer.team-name=Consents and Authorisations Team
branding.customer.legal-name=Oil and Gas Authority
branding.customer.legal-mnemonic=OGA
branding.customer.registered-number=09666504
branding.customer.vat-number=249433979
branding.customer.address=Sanctuary Buildings, 20 Great Smith Street, London, SW1P 3BT

# Accessibility
accessibility.statement-prepared-date=12 June 2024
accessibility.statement-last-review-date=12 June 2024
accessibility.service-last-test-date=3 June 2024
accessibility.service-last-tested-by=Fivium Ltd
accessibility.design-system-last-test-date=10 November 2020
accessibility.production-guidance-url=https://www.nstauthority.co.uk/regulatory-information/licensing-and-consents/consents/production-consents/
accessibility.flare-and-vent-guidance-url=https://www.nstauthority.co.uk/regulatory-information/licensing-and-consents/consents/flaring-and-venting/

# Support
service.business-support-contact.name=${branding.customer.mnemonic}
service.business-support-contact.email=${branding.customer.email}

service.technical-support-contact.name=UKOP service desk
service.technical-support-contact.email=ukop@nstauthority.co.uk
service.technical-support-contact.phone=0300 067 1682

# Analytics
analytics.serviceAnalyticIdentifier=${FCS_ANALYTICS_SERVICE_IDENTIFIER:}
analytics.energyPortalAnalyticIdentifier=${FCS_ANALYTICS_ENERGY_PORTAL_IDENTIFIER:}

# Digital signature
# Do not change these fields without also updating the GlobalSign identity. They must match exactly.
digital-signature.organisation=Oil and Gas Authority
digital-signature.email=ukop@nstauthority.co.uk
digital-signature.state=Aberdeenshire
digital-signature.country=GB
digital-signature.locality=Aberdeen
digital-signature.reason=On behalf of the Secretary of State
digital-signature.location=North Sea Transition Authority
# The following can safely be changed independently of any configuration within GlobalSign
digital-signature.common-name=${branding.customer.legal-name}
digital-signature.line-1=Digitally signed by and on behalf of the ${branding.customer.legal-name}
digital-signature.line-3=${branding.customer.legal-name}

# Service
service.base-url=${FCS_SERVICE_BASE_URL}${server.servlet.context-path}

# Application
application.application-no-start-value=${fcs.application-no-start-value}

# Freemarker
spring.freemarker.settings.output_format=HTMLOutputFormat
spring.freemarker.settings.template_exception_handler=rethrow
spring.freemarker.settings.number_format=c
spring.freemarker.suffix=.ftl

# Datasource
spring.datasource.url=${database.url}
spring.datasource.username=fcs_app
spring.datasource.password=${schema.password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=fcs
spring.jpa.properties.hibernate.cdi.extensions=false

# Don't allow queries to be executed in views or entities to be automatically flushed outside of an explicit transaction
spring.jpa.open-in-view=false

# Flyway
spring.flyway.schemas=fcs
spring.flyway.placeholders.application-schema=${spring.flyway.schemas}

# jOOQ
jooq.schema=fcs

# SAML
saml.registration-id=saml

#energy portal api
energy-portal-api.url=${ENERGY_PORTAL_API_URL}
energy-portal-api.pre-shared-key=${ENERGY_PORTAL_API_PSK}

energy-portal.registration-url=${FCS_ENERGY_PORTAL_REGISTRATION_URL}
energy-portal.logout-url=${FCS_ENERGY_PORTAL_LOGOUT_URL}

# file upload library
file-upload.s3.access-key=${S3_ACCESS_TOKEN}
file-upload.s3.secret-token=${S3_SECRET_TOKEN}
file-upload.s3.default-bucket=${S3_DEFAULT_BUCKET}
file-upload.s3.endpoint=${S3_ENDPOINT:s3.eu-west-2.amazonaws.com}
file-upload.s3.signing-region=${S3_SIGNING_REGION:eu-west-2}
file-upload.s3.proxy.host=${S3_PROXY_HOST}
file-upload.s3.proxy.port=${S3_PROXY_PORT}
file-upload.clamav.host=${CLAMAV_HOST}
file-upload.clamav.port=${CLAMAV_PORT}
file-upload.clamav.timeout=PT1M
file-upload.default-permitted-file-extensions=bmp, csv, doc, docx, jpeg, jpg, pdf, png, txt, xls, xlsx
file-upload.default-maximum-file-size=50MB
spring.servlet.multipart.max-file-size=${file-upload.default-maximum-file-size}
spring.servlet.multipart.max-request-size=${spring.servlet.multipart.max-file-size}

# Digital Payments Library
digital-payments-library.govukpay.api-key=${GOV_UK_PAY_API_KEY}

# Energy Portal Access Library
energy-portal.access-api.base-url=${FCS_ENERGY_PORTAL_TEAM_ACCESS_API_BASE_URL}
energy-portal.access-api.token=${FCS_ENERGY_PORTAL_TEAM_ACCESS_API_TOKEN}

# Notification library
digital-notification-library.govuk-notify.api-key=${FCS_GOV_NOTIFY_API_KEY:}
digital-notification-library.test-mode.email-recipients=${FCS_EMAIL_TEST_RECIPIENTS:}
# Test mode requires a sms recipient regardless of if you need sms. As we don't send sms default to a random number.
digital-notification-library.test-mode.sms-recipients=0123456789

# Feedback management service
fms.url-base=${FCS_FMS_URL_BASE}
fms.connectionTimeoutSeconds=${FCS_FMS_CONNECTION_TIMEOUT_SECONDS:20}
fms.saveFeedbackUrl=${FCS_FMS_SUBMIT_ENDPOINT:/api/v1/save-feedback}
fms.service-name=FCS
fms.presharedKey=${FCS_FMS_PRESHARED_KEY}

# EPMQ
epmq.sns-sqs.aws-access-key-id=${FCS_EPMQ_SNS_SQS_AWS_ACCESS_KEY_ID:}
epmq.sns-sqs.aws-secret-access-key=${FCS_EPMQ_SNS_SQS_AWS_SECRET_ACCESS_KEY:}
epmq.sns-sqs.aws-region-id=${FCS_EPMQ_SNS_SQS_AWS_REGION_ID:eu-west-2}
epmq.environment-suffix=${FCS_EPMQ_ENVIRONMENT_SUFFIX:}

management.endpoints.web.exposure.include=health,application-submitted-sns-message

actuator.admin-user-password=${FCS_ACTUATOR_ADMIN_USER_PASSWORD:}

#Spring Session properties
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=never
spring.session.jdbc.table-name=${spring.jpa.properties.hibernate.default_schema}.SPRING_SESSION
server.servlet.session.timeout=180m

logging.pattern.correlation=[%X{CORRELATION_ID}] 
