database.url=jdbc:postgresql://${FCS_DATABASE_URL}
schema.password=${FCS_DATABASE_PASSWORD}
spring.flyway.placeholders.datawarehouse-user-password=${FCS_DATAWAREHOUSE_USER_PASSWORD}

saml.entity-id=${FCS_SAML_ENTITY_ID}
saml.login-url=${FCS_SAML_LOGIN_URL}
saml.certificate=${FCS_SAML_CERTIFICATE}

saml.consumer-service-location=${FCS_SAML_BASE_URL}${server.servlet.context-path}/login/saml2/sso/saml

# Flyway
spring.flyway.out-of-order=${FCS_ENABLE_FLYWAY_OUT_OF_ORDER:false}

# Application references
fcs.application-no-start-value=${FCS_APPLICATION_NUMBER_START_VALUE}

# Notification library
digital-notification-library.mode=${FCS_NOTIFICATION_MODE:}

# Metrics
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.statsd.metrics.export.enabled=${FCS_ENABLE_STATSD}
management.statsd.metrics.export.host=${FCS_STATSD_HOST}
management.statsd.metrics.export.port=${FCS_STATSD_PORT}
management.statsd.metrics.export.flavor=${FCS_METRICS_EXPORT_TYPE}
management.metrics.tags.instance=${FCS_METRICS_INSTANCE_TAG}
management.metrics.tags.source-type=${FCS_METRICS_SOURCE_TYPE_TAG}

# FTSS
ftss.base-url=${FCS_FTSS_BASE_URL}
ftss.api-key=${FCS_FTSS_API_KEY}