server.servlet.context-path=${FCS_CONTEXT_PATH:/fcs}

# Service branding
branding.service.name=Field Consents
branding.service.mnemonic=FCS

branding.customer.name=North Sea Transition Authority
branding.customer.mnemonic=NSTA

# Freemarker
spring.freemarker.settings.output_format=HTMLOutputFormat
spring.freemarker.settings.template_exception_handler=rethrow
spring.freemarker.suffix=.ftl

# Datasource
spring.datasource.url=${database.url}
spring.datasource.username=fcs
spring.datasource.password=${schema.password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Don't allow queries to be executed in views or entities to be automatically flushed outside of an explicit transaction
spring.jpa.open-in-view=false

# Flyway
spring.flyway.default-schema=flyway