itportal-base-url=https://nsta.itportal.dev.fivium.co.uk
service.base-url=http://localhost:8080${server.servlet.context-path}

spring.docker.compose.file=devtools/local-dev-compose.yml

service.error.include-stacktrace=true

spring.flyway.placeholders.datawarehouse-user-password=dev1

saml.entity-id=energy-portal-accounts-service-dev
saml.login-url=${itportal-base-url}/accounts/saml/login

energy-portal.logout-pre-shared-key=dev
energy-portal.logout-url=${itportal-base-url}/accounts/service-provider-sign-out

saml.certificate=-----BEGIN CERTIFICATE----- \n\
MIICWDCCAcGgAwIBAgIJAISi9077RhJfMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV \n\
BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX \n\
aWRnaXRzIFB0eSBMdGQwHhcNMTgwMjIyMTQyMjE4WhcNMTkwMjIyMTQyMjE4WjBF \n\
MQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50 \n\
ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKB \n\
gQDLOCvy3uiMra1tR8UZrXyR5yIb1lrM18S+/9NYP3dY/seGx/FMt7Cq4Jny6kVM \n\
hSXC6C79ht8bLW6twA56WkJU6CjVKGDWljCserrYknj4DutNPmOMW//Ns395+sRP \n\
wagoPEIlQejBIbNNVIf9q5EZbtAFgffD1DjmecnNpZIEmQIDAQABo1AwTjAdBgNV \n\
HQ4EFgQUnn03ZFAyi31UyVINt4PwiDqlm8EwHwYDVR0jBBgwFoAUnn03ZFAyi31U \n\
yVINt4PwiDqlm8EwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOBgQCNSTJ9 \n\
QX6ojK18USkHrGhUQBVRUceVsN9Ztmt3Im3213YIhPOq7BGB6xOp+r8s+AteLR3R \n\
ap5sR3Qs4WXEXUy4bfWAtx4hSRBR7jFqAG6uq4Ixh/YDU0lqETfdzIG10606huBX \n\
9Et8EhuI3x8evCm3FCEaXPlKLW/hI0ppBInDdw== \n\
-----END CERTIFICATE-----

saml.consumer-service-location=http://localhost:8080${server.servlet.context-path}/login/saml2/sso/saml

# flyway
spring.flyway.out-of-order=true

#energy portal api

# Use below for local testing only
#energy-portal-api.url=http://localhost:8081/graphql
# Use below when testing against deployed EPA
energy-portal-api.url=${itportal-base-url}/portal-api/graphql
energy-portal-api.pre-shared-key=fcs-dev

energy-portal.registration-url=${itportal-base-url}/accounts/register

# energy portal access api
energy-portal.workbasket-url=${itportal-base-url}/engedudev1/fox
energy-portal.access-api.base-url=${itportal-base-url}/edufox5dev
energy-portal.access-api.token=dev

# Application references
fcs.application-no-start-value=8000

# file upload library
file-upload.s3.credentials.access-key-id=minio
file-upload.s3.credentials.secret-access-key=minio123
file-upload.s3.endpoint-override=http://127.0.0.1:9000
file-upload.clamav.host=localhost
file-upload.clamav.port=3310

# Notification library
digital-notification-library.mode=test

# Metrics
management.statsd.metrics.export.enabled=false

# FTSS
ftss.base-url=${itportal-base-url}/ftss
ftss.api-key=dev1-fcs

# Feedback management service
fms.url-base=${itportal-base-url}/fmsdev
fms.presharedKey=dev

actuator.admin-user-password=dev

# Analytics
analytics.serviceAnalyticIdentifier=G-VGMEJTJC2C
analytics.energyPortalAnalyticIdentifier=G-QLX4YRDD0K

# Logging
logging.level.uk.co.nstauthority.fieldconsents.application.bulkcaseactions.bulkissueconsents=debug

# Energy Portal Accounts
energy-portal-accounts.preshared-key=dev1
energy-portal-accounts.disable-message-sending=true
spring.config.import=classpath:config/well-known-organisation-groups.yaml