server.error.path=/error
server.error.whitelabel.enabled=false
server.servlet.context-path=${FCS_CONTEXT_PATH:/fcs}

# Service branding
branding.service.name=Field Consents
branding.service.mnemonic=FCS

branding.customer.name=North Sea Transition Authority
branding.customer.mnemonic=NSTA

# Freemarker
spring.freemarker.settings.output_format=HTMLOutputFormat
spring.freemarker.settings.template_exception_handler=rethrow
spring.freemarker.suffix=.ftl

# Datasource
spring.datasource.url=${database.url}
spring.datasource.username=fcs_app
spring.datasource.password=${schema.password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=fcs

# Don't allow queries to be executed in views or entities to be automatically flushed outside of an explicit transaction
spring.jpa.open-in-view=false

# Flyway
spring.flyway.schemas=fcs

# SAML
saml.registration-id=saml
