database.url=jdbc:postgresql://${FCS_DATABASE_URL}
schema.password=${FCS_DATABASE_PASSWORD}
spring.flyway.placeholders.datawarehouse-user-password=${FCS_DATAWAREHOUSE_USER_PASSWORD}

saml.entity-id=${FCS_SAML_ENTITY_ID}
saml.login-url=${FCS_SAML_LOGIN_URL}
saml.certificate=${FCS_SAML_CERTIFICATE}

saml.consumer-service-location=${FCS_SAML_BASE_URL}${server.servlet.context-path}/login/saml2/sso/saml

# Flyway
spring.flyway.out-of-order=${FCS_ENABLE_FLYWAY_OUT_OF_ORDER:false}

# Application references
fcs.application-no-start-value=${FCS_APPLICATION_NUMBER_START_VALUE}
