package uk.co.nstauthority.fieldconsents.validation;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import org.springframework.validation.Errors;
import org.springframework.validation.FieldError;

public class ValidatorTestingUtil {

  /**
   * Produces a map of error pairs generated by the validation process in case one or more
   * field values of the form under test are rejected. The error pair consists of the formField linked to the error
   * and the corresponding errorMessage
   * @param errors stores validation errors for a specific form under test
   * @return the list of error messages found when a form is being validated
   */
  public static Map<String, List<String>> getErrorsFieldsAndMessages(Errors errors){
    return errors.getAllErrors().stream()
        .filter(objectError -> objectError instanceof FieldError)
        .map(objectError -> (FieldError) objectError)
        .collect(
            Collectors.groupingBy(FieldError::getField, Collectors.mapping(FieldError::getDefaultMessage, Collectors.toList())));
  }
}
