package uk.co.nstauthority.fieldconsents.assets.fields;

import java.util.List;

public class FieldData {

  public static List<FieldJson> fields = List.of(
      new FieldJson(1164, "AFFLECK"),
      new FieldJson(3672, "AIRTH COAL BED METHANE DEVT."),
      new FieldJson(965, "ALBA"),
      new FieldJson(1663, "ALBURY"),
      new FieldJson(2951, "ALDER"),
      new FieldJson(3052, "ALISON-KX[CONO.][pt.of ALISON]"),
      new FieldJson(1699, "ALISON[VENTURE][pt.of ALISON]"),
      new FieldJson(6516, "ALMA"),
      new FieldJson(6688, "ALVHEIM"),
      new FieldJson(885, "ALWYN NORTH"),
      new FieldJson(886, "AMETHYST EAST"),
      new FieldJson(966, "AMETHYST WEST"),
      new FieldJson(990, "ANDREW"),
      new FieldJson(967, "ANGLIA"),
      new FieldJson(992, "ANN"),
      new FieldJson(998, "APOLLO [pt of JUNO]"),
      new FieldJson(882, "ARBROATH"),
      new FieldJson(993, "ARKWRIGHT"),
      new FieldJson(6214, "ARRAN"),
      new FieldJson(1543, "ARTHUR"),
      new FieldJson(6012, "ATHENA"),
      new FieldJson(888, "AUDREY"),
      new FieldJson(889, "AUK"),
      new FieldJson(6152, "AUK NORTH"),
      new FieldJson(6172, "AVINGTON"),
      new FieldJson(4657, "BABBAGE"),
      new FieldJson(6292, "BACCHUS"),
      new FieldJson(1409, "BAINS"),
      new FieldJson(2431, "BAIRD"),
      new FieldJson(890, "BALMORAL"),
      new FieldJson(1552, "BANFF"),
      new FieldJson(1153, "BARDOLINO"),
      new FieldJson(5814, "BARNACLE"),
      new FieldJson(891, "BARQUE"),
      new FieldJson(2191, "BARQUE SOUTH"),
      new FieldJson(6394, "BARRA (part of WESTERN ISLES)"),
      new FieldJson(892, "BEATRICE"),
      new FieldJson(4935, "BEAULY"),
      new FieldJson(1645, "BECKINGHAM WEST"),
      new FieldJson(1026, "BEINN"),
      new FieldJson(5032, "BELL"),
      new FieldJson(4892, "BELL [CONOCO][pt. of BELL]"),
      new FieldJson(2831, "BELL [PERENCO][pt. of BELL]"),
      new FieldJson(6398, "BENTLEY"),
      new FieldJson(893, "BERYL"),
      new FieldJson(994, "BESSEMER"),
      new FieldJson(6246, "BEVERCOTES COAL MINE VENT"),
      new FieldJson(2551, "BIG DOTTY [pt. of HEWETT]"),
      new FieldJson(6253, "BILSTHORPE COLLIERY MINE VENT"),
      new FieldJson(1027, "BIRCH"),
      new FieldJson(4072, "BITTERN"),
      new FieldJson(6413, "BLACKBIRD"),
      new FieldJson(6335, "BLAKE"),
      new FieldJson(1201, "BLANE [UK]"),
      new FieldJson(5732, "BOA [UK]"),
      new FieldJson(6689, "BOA(CROSS BORDER)"),
      new FieldJson(1023, "BOULTON"),
      new FieldJson(6072, "BOULTON H"),
      new FieldJson(5372, "BOYLE"),
      new FieldJson(1536, "BRAE"),
      new FieldJson(3295, "BRAE-CENTRAL [Part of BRAE]"),
      new FieldJson(3294, "BRAE-NORTH [Part of BRAE]"),
      new FieldJson(3296, "BRAE-SOUTH [Part of BRAE]"),
      new FieldJson(1030, "BRAEMAR"),
      new FieldJson(6192, "BREAGH"),
      new FieldJson(5534, "BRECHIN"),
      new FieldJson(1505, "BRENDA"),
      new FieldJson(895, "BRENT"),
      new FieldJson(1042, "BRIGANTINE A"),
      new FieldJson(4692, "BRIGANTINE B"),
      new FieldJson(5052, "BRIGANTINE C"),
      new FieldJson(5252, "BRIGANTINE D"),
      new FieldJson(3892, "BRIMMOND"),
      new FieldJson(2005, "BRITANNIA"),
      new FieldJson(1652, "BROCKHAM"),
      new FieldJson(5332, "BRODGAR"),
      new FieldJson(1003, "BROOM"),
      new FieldJson(4652, "BROWN"),
      new FieldJson(969, "BRUCE"),
      new FieldJson(896, "BUCHAN"),
      new FieldJson(996, "BUCKLAND"),
      new FieldJson(6032, "BURE WEST [pt. of BURE]"),
      new FieldJson(897, "BURE [pt of THAMES COMPLEX]"),
      new FieldJson(5752, "BURGHLEY"),
      new FieldJson(5272, "BUZZARD"),
      new FieldJson(6249, "CADEBY COAL MINE VENT"),
      new FieldJson(1385, "CAISTER [BUNTER]"),
      new FieldJson(1599, "CAISTER [CARBONIFEROUS]"),
      new FieldJson(1205, "CALDER"),
      new FieldJson(2571, "CALEDONIA"),
      new FieldJson(5333, "CALLANISH"),
      new FieldJson(1632, "CALLISTO"),
      new FieldJson(6092, "CALLISTO NORTH"),
      new FieldJson(1656, "CALOW"),
      new FieldJson(6492, "CALVERTON COAL MINE VENT"),
      new FieldJson(1081, "CAPTAIN"),
      new FieldJson(5632, "CARAVEL"),
      new FieldJson(2511, "CARNOUSTIE"),
      new FieldJson(5132, "CARRACK"),
      new FieldJson(6115, "CAUSEWAY"),
      new FieldJson(1399, "CAVENDISH"),
      new FieldJson(6472, "CAWDOR"),
      new FieldJson(6618, "CAYLEY"),
      new FieldJson(6114, "CERES"),
      new FieldJson(971, "CHANTER"),
      new FieldJson(1082, "CHESTNUT"),
      new FieldJson(5772, "CHEVIOT"),
      new FieldJson(1074, "CHISWICK"),
      new FieldJson(997, "CLAIR"),
      new FieldJson(5013, "CLAPHAM"),
      new FieldJson(900, "CLAYMORE"),
      new FieldJson(901, "CLEETON"),
      new FieldJson(902, "CLIPPER NORTH"),
      new FieldJson(1083, "CLIPPER SOUTH"),
      new FieldJson(903, "CLYDE"),
      new FieldJson(4532, "COLD HANWORTH"),
      new FieldJson(6117, "COLUMBUS"),
      new FieldJson(6433, "CONRIE"),
      new FieldJson(6397, "CONWY"),
      new FieldJson(1620, "COOK"),
      new FieldJson(6535, "CORFE"),
      new FieldJson(904, "CORMORANT NORTH"),
      new FieldJson(3812, "CORVETTE"),
      new FieldJson(1646, "CROSBY WARREN"),
      new FieldJson(1160, "CURLEW B + D"),
      new FieldJson(2231, "CURLEW C"),
      new FieldJson(2852, "CUTTER"),
      new FieldJson(6132, "CYGNUS"),
      new FieldJson(906, "CYRUS"),
      new FieldJson(6655, "DA TEST"),
      new FieldJson(1191, "DALTON"),
      new FieldJson(1033, "DAVY"),
      new FieldJson(3873, "DAVY EAST"),
      new FieldJson(2731, "DEBORAH [pt. of HEWETT]"),
      new FieldJson(1527, "DELILAH"),
      new FieldJson(907, "DELLA"),
      new FieldJson(1404, "DEVENICK"),
      new FieldJson(908, "DEVERON"),
      new FieldJson(6232, "DOE GREEN COAL BED METHANE"),
      new FieldJson(6013, "DON SOUTH WEST"),
      new FieldJson(5792, "DONAN [MAERSK]"),
      new FieldJson(1192, "DOUGLAS"),
      new FieldJson(5412, "DOUGLAS WEST"),
      new FieldJson(1084, "DRAKE [pt of ARMADA COMPLEX]"),
      new FieldJson(5832, "DUART"),
      new FieldJson(1387, "DUNBAR"),
      new FieldJson(911, "DUNLIN"),
      new FieldJson(1085, "DUNLIN SOUTH WEST"),
      new FieldJson(6112, "DURANGO"),
      new FieldJson(968, "EAST BRAE"),
      new FieldJson(1396, "EAST GLENTWORTH"),
      new FieldJson(1015, "EAST SEAN"),
      new FieldJson(6687, "EDVARD GREIG"),
      new FieldJson(1516, "EGRET"),
      new FieldJson(912, "EIDER"),
      new FieldJson(6678, "EKOFISK"),
      new FieldJson(1621, "ELGIN"),
      new FieldJson(1637, "ELLON"),
      new FieldJson(3372, "ELSWICK"),
      new FieldJson(1034, "ENOCH [UK]"),
      new FieldJson(6691, "ENOCH(CROSS BORDER)"),
      new FieldJson(1088, "ENSIGN"),
      new FieldJson(6053, "ERIS"),
      new FieldJson(1557, "ERSKINE"),
      new FieldJson(1090, "ETTRICK"),
      new FieldJson(1631, "EUROPA"),
      new FieldJson(973, "EVEREST"),
      new FieldJson(1629, "EXCALIBUR"),
      new FieldJson(6393, "FALCON"),
      new FieldJson(1647, "FARLEYS WOOD"),
      new FieldJson(5532, "FARRAGON"),
      new FieldJson(6558, "FIONN"),
      new FieldJson(4792, "FISKERTON AIRFIELD"),
      new FieldJson(1010, "FLEMING [pt of ARMADA COMPLEX]"),
      new FieldJson(6494, "FLORENCE COAL MINE VENT"),
      new FieldJson(1547, "FLYNDRE [UK]"),
      new FieldJson(2056, "FOINAVEN"),
      new FieldJson(915, "FORTIES"),
      new FieldJson(5533, "FORVIE NORTH"),
      new FieldJson(1069, "FRAM"),
      new FieldJson(1091, "FRANKLIN"),
      new FieldJson(5972, "FRICKLEY COAL MINE VENT"),
      new FieldJson(917, "FULMAR"),
      new FieldJson(4372, "GADWALL"),
      new FieldJson(1657, "GALAHAD"),
      new FieldJson(6517, "GALIA"),
      new FieldJson(999, "GALLEON"),
      new FieldJson(1036, "GALLEY"),
      new FieldJson(974, "GANNET A"),
      new FieldJson(975, "GANNET B"),
      new FieldJson(976, "GANNET C"),
      new FieldJson(977, "GANNET D"),
      new FieldJson(1038, "GANNET E"),
      new FieldJson(1150, "GANNET F"),
      new FieldJson(4833, "GANNET G"),
      new FieldJson(1051, "GANYMEDE"),
      new FieldJson(1859, "GARROW"),
      new FieldJson(6685, "GAUPE"),
      new FieldJson(1000, "GAWAIN"),
      new FieldJson(6495, "GEDLING COAL MINE VENT"),
      new FieldJson(6681, "GJOA"),
      new FieldJson(918, "GLAMIS"),
      new FieldJson(5012, "GLENELG"),
      new FieldJson(6392, "GODWIN"),
      new FieldJson(6453, "GOLDBORNE COAL MINE VENT"),
      new FieldJson(6054, "GOLDEN EAGLE"),
      new FieldJson(1670, "GOODWORTH"),
      new FieldJson(4912, "GOOSANDER"),
      new FieldJson(1533, "GRANT"),
      new FieldJson(5992, "GRIMETHORPE COAL MINE VENT"),
      new FieldJson(1530, "GROUSE"),
      new FieldJson(1181, "GROVE"),
      new FieldJson(1388, "GRYPHON"),
      new FieldJson(1037, "GUILLEMOT A"),
      new FieldJson(4612, "GUILLEMOT NORTH WEST"),
      new FieldJson(1534, "GUILLEMOT WEST"),
      new FieldJson(1600, "GUINEVERE"),
      new FieldJson(6676, "GYDA"),
      new FieldJson(1622, "HALLEY"),
      new FieldJson(1002, "HAMILTON"),
      new FieldJson(2632, "HAMILTON EAST"),
      new FieldJson(1193, "HAMILTON NORTH"),
      new FieldJson(3912, "HANNAY"),
      new FieldJson(1035, "HARDING"),
      new FieldJson(6597, "HARRIER"),
      new FieldJson(6499, "HARRIS (part of WESTERN ISLES)"),
      new FieldJson(1648, "HATFIELD"),
      new FieldJson(1096, "HAWKINS [pt of ARMADA COMPLEX]"),
      new FieldJson(921, "HEATHER"),
      new FieldJson(6684, "HEIMDAL"),
      new FieldJson(1555, "HELVELLYN"),
      new FieldJson(6496, "HEM HEATH COAL MINE VENT"),
      new FieldJson(1040, "HERON"),
      new FieldJson(3595, "HERRIARD [pt. of HUMBLY GROVE]"),
      new FieldJson(922, "HEWETT"),
      new FieldJson(6238, "HICKLETON COAL MINE VENT"),
      new FieldJson(923, "HIGHLANDER"),
      new FieldJson(924, "HORNDEAN"),
      new FieldJson(2058, "HORNE"),
      new FieldJson(1097, "HOTON"),
      new FieldJson(5993, "HOUGHTON MAIN COAL MINE VENT"),
      new FieldJson(1152, "HOWE"),
      new FieldJson(1041, "HUDSON"),
      new FieldJson(1679, "HUMBLY GROVE"),
      new FieldJson(1863, "HUNTER"),
      new FieldJson(6133, "HUNTINGTON"),
      new FieldJson(1635, "HYDE"),
      new FieldJson(927, "INDE SOUTH WEST"),
      new FieldJson(4432, "INDEFATIGABLE"),
      new FieldJson(2001, "INDE[PERENCO][pt.of INDEFATIG]"),
      new FieldJson(1012, "IONA"),
      new FieldJson(5612, "IRONVILLE"),
      new FieldJson(6216, "ISLAY"),
      new FieldJson(6679, "ISLAY(CROSS BORDER)"),
      new FieldJson(6052, "JACKY"),
      new FieldJson(4333, "JADE"),
      new FieldJson(5512, "JAMES"),
      new FieldJson(1005, "JANICE"),
      new FieldJson(6215, "JASMINE"),
      new FieldJson(1981, "JOANNE"),
      new FieldJson(986, "JOHNSTON"),
      new FieldJson(1006, "JUDY"),
      new FieldJson(6273, "JULIET"),
      new FieldJson(5892, "JURA"),
      new FieldJson(6690, "KAMELEON"),
      new FieldJson(6272, "KATY"),
      new FieldJson(4812, "KEDDINGTON"),
      new FieldJson(1043, "KEITH"),
      new FieldJson(6617, "KELLS"),
      new FieldJson(5872, "KELVIN"),
      new FieldJson(4552, "KESTREL"),
      new FieldJson(1044, "KETCH"),
      new FieldJson(6556, "KEW"),
      new FieldJson(5472, "KILMAR"),
      new FieldJson(6515, "KIMMERIDGE"),
      new FieldJson(1105, "KINGFISHER"),
      new FieldJson(6497, "KINGS MILL HOSPITAL CM VENT"),
      new FieldJson(6213, "KINNOULL"),
      new FieldJson(1653, "KIRBY MISPERTON"),
      new FieldJson(6372, "KIRKLEATHAM"),
      new FieldJson(1649, "KIRKLINGTON"),
      new FieldJson(932, "KITTIWAKE"),
      new FieldJson(6683, "KNARR"),
      new FieldJson(2394, "KYLE"),
      new FieldJson(4412, "LAGGAN"),
      new FieldJson(1779, "LANCELOT"),
      new FieldJson(2026, "LARCH {TREES}"),
      new FieldJson(3596, "LEMAN BANK"),
      new FieldJson(933, "LEMAN [PERENCO][pt. of LEMAN]"),
      new FieldJson(2004, "LEMAN [SHELL][pt. of LEMAN]"),
      new FieldJson(1941, "LENNOX"),
      new FieldJson(1395, "LEVEN"),
      new FieldJson(1678, "LIDSEY"),
      new FieldJson(2552, "LITTLE DOTTY [pt. of HEWETT]"),
      new FieldJson(6514, "LLANGEINOR COAL BED METHANE"),
      new FieldJson(5613, "LLAY MAIN COAL MINE VENT"),
      new FieldJson(6134, "LOCHRANZA"),
      new FieldJson(5852, "LOIRSTON"),
      new FieldJson(978, "LOMOND"),
      new FieldJson(1650, "LONG CLAWSON"),
      new FieldJson(3433, "LOYAL [Part of SCHIEHALLION]"),
      new FieldJson(4192, "LYBSTER"),
      new FieldJson(979, "LYELL"),
      new FieldJson(1503, "MACCULLOCH"),
      new FieldJson(1009, "MACHAR"),
      new FieldJson(1126, "MACLURE"),
      new FieldJson(4472, "MADOES"),
      new FieldJson(936, "MAGNUS"),
      new FieldJson(3752, "MAGNUS SOUTH"),
      new FieldJson(1144, "MALLARD"),
      new FieldJson(4353, "MALORY"),
      new FieldJson(1654, "MALTON"),
      new FieldJson(6250, "MANVERS COAL MINE VENT"),
      new FieldJson(2432, "MARIA"),
      new FieldJson(1655, "MARISHES"),
      new FieldJson(6235, "MARKHAM COAL MINE VENT"),
      new FieldJson(1390, "MARKHAM [UK]"),
      new FieldJson(1103, "MARNOCK [pt. of MARNOCK-SKUA]"),
      new FieldJson(3772, "MARNOCK-SKUA"),
      new FieldJson(6680, "MARTIN LINGE"),
      new FieldJson(6312, "MAULE"),
      new FieldJson(5292, "MCADAM [Part of CMS Phase 3]"),
      new FieldJson(1410, "MEDWIN"),
      new FieldJson(1526, "MERCURY"),
      new FieldJson(4669, "MERGANSER"),
      new FieldJson(4332, "MERLIN"),
      new FieldJson(1106, "MILLOM"),
      new FieldJson(5653, "MIMAS"),
      new FieldJson(4654, "MINERVA [pt of JUNO]"),
      new FieldJson(2061, "MINKE"),
      new FieldJson(2060, "MIRREN"),
      new FieldJson(1413, "MONAN"),
      new FieldJson(6242, "MONK BRETTON COAL MINE VENT"),
      new FieldJson(939, "MONTROSE"),
      new FieldJson(3072, "MORDRED"),
      new FieldJson(6616, "MORRONE"),
      new FieldJson(1414, "MUNGO"),
      new FieldJson(5552, "MUNRO"),
      new FieldJson(941, "MURCHISON [UK]"),
      new FieldJson(5692, "MURCHISON[NON UK]"),
      new FieldJson(1392, "MURDOCH"),
      new FieldJson(6073, "MURDOCH K"),
      new FieldJson(1366, "NELSON"),
      new FieldJson(2091, "NEPTUNE"),
      new FieldJson(942, "NESS"),
      new FieldJson(5592, "NETHAN"),
      new FieldJson(1638, "NETTLEHAM"),
      new FieldJson(1011, "NEVIS"),
      new FieldJson(6254, "NEWMARKET COLLIERY MINE VENT"),
      new FieldJson(1541, "NEWSHAM"),
      new FieldJson(4872, "NEWTON-ON-TRENT"),
      new FieldJson(5672, "NICOL"),
      new FieldJson(943, "NINIAN"),
      new FieldJson(3212, "NINIAN-COLUMBA B/D TERRACE"),
      new FieldJson(2532, "NINIAN-COLUMBA D TERRACE"),
      new FieldJson(2531, "NINIAN-COLUMBA E TERRACE"),
      new FieldJson(5092, "NORTH DAVY"),
      new FieldJson(1391, "NORTH MORECAMBE"),
      new FieldJson(949, "NORTH SEAN [Part of SEAN]"),
      new FieldJson(956, "NORTH VALIANT"),
      new FieldJson(1821, "NUGGETS N1"),
      new FieldJson(1549, "NUGGETS N2"),
      new FieldJson(1548, "NUGGETS N3"),
      new FieldJson(1550, "NUGGETS N4"),
      new FieldJson(6252, "OGMORE VALE COAL MINE VENT"),
      new FieldJson(2691, "ORCA UK"),
      new FieldJson(1398, "ORION"),
      new FieldJson(944, "OSPREY"),
      new FieldJson(1207, "OTTER"),
      new FieldJson(6513, "PADON"),
      new FieldJson(1453, "PALMERS WOOD"),
      new FieldJson(6255, "PARSONAGE COAL MINE VENT"),
      new FieldJson(6512, "PEEL"),
      new FieldJson(1046, "PELICAN"),
      new FieldJson(1531, "PENGUIN A {PENGUIN WEST}"),
      new FieldJson(1109, "PENGUIN C {pt of PENGUIN EAST}"),
      new FieldJson(1110, "PENGUIN D {pt of PENGUIN EAST}"),
      new FieldJson(6576, "PENGUIN EAST"),
      new FieldJson(6575, "PENGUIN WEST"),
      new FieldJson(6432, "PEREGRINE"),
      new FieldJson(1942, "PERTH"),
      new FieldJson(945, "PETRONELLA"),
      new FieldJson(1384, "PICKERILL"),
      new FieldJson(5352, "PICKERING"),
      new FieldJson(1142, "PICT"),
      new FieldJson(3972, "PIERCE"),
      new FieldJson(1367, "PIPER"),
      new FieldJson(1532, "PLAYFAIR"),
      new FieldJson(6595, "PONTYCYMMER COAL MINE VENT"),
      new FieldJson(6233, "POTTERIES COAL BED METHANE"),
      new FieldJson(6251, "PRINCE OF WALES COAL MINE VENT"),
      new FieldJson(26570, "Pathfinder test field"),
      new FieldJson(6555, "Penguin E {pt of PENGUIN EAST}"),
      new FieldJson(3615, "RAVENSPURN"),
      new FieldJson(2002, "RAVENSPURN N[pt.of RAVENSPURN]"),
      new FieldJson(1363, "RAVENSPURN S[pt.of RAVENSPURN]"),
      new FieldJson(1639, "REMPSTONE"),
      new FieldJson(6686, "REV"),
      new FieldJson(5112, "RHUM"),
      new FieldJson(6557, "RHYL"),
      new FieldJson(4694, "RITA"),
      new FieldJson(5153, "ROCHELLE"),
      new FieldJson(4934, "ROSE"),
      new FieldJson(1047, "ROSS"),
      new FieldJson(947, "ROUGH"),
      new FieldJson(4312, "SALTFLEETBY"),
      new FieldJson(981, "SALTIRE"),
      new FieldJson(5473, "SATURN (ANNABEL)"),
      new FieldJson(5432, "SATURN (ATLAS,HYPERION,RHEA)"),
      new FieldJson(5712, "SAXON"),
      new FieldJson(4112, "SCAMPTON"),
      new FieldJson(1451, "SCAMPTON NORTH"),
      new FieldJson(948, "SCAPA"),
      new FieldJson(2711, "SCHIEHALLION"),
      new FieldJson(1014, "SCHOONER"),
      new FieldJson(1112, "SCOTER"),
      new FieldJson(982, "SCOTT"),
      new FieldJson(1016, "SEDGWICK [PT. OF WEST BRAE]"),
      new FieldJson(6116, "SEVEN SEAS"),
      new FieldJson(1113, "SEYMOUR"),
      new FieldJson(5755, "SHAMROCK"),
      new FieldJson(6619, "SHAW"),
      new FieldJson(1517, "SHEARWATER"),
      new FieldJson(6245, "SHERWOOD (OLD MILL LANE) VENT"),
      new FieldJson(6237, "SHIREBROOK COAL MINE VENT"),
      new FieldJson(1640, "SINGLETON"),
      new FieldJson(1633, "SINOPE"),
      new FieldJson(1057, "SKENE"),
      new FieldJson(4273, "SKIFF"),
      new FieldJson(1114, "SKUA [pt. of MARNOCK-SKUA]"),
      new FieldJson(2055, "SOLAN"),
      new FieldJson(905, "SOUTH CORMORANT"),
      new FieldJson(940, "SOUTH MORECAMBE"),
      new FieldJson(950, "SOUTH SEAN [Part of SEAN]"),
      new FieldJson(957, "SOUTH VALIANT"),
      new FieldJson(1641, "STAINTON"),
      new FieldJson(6113, "STAMFORD"),
      new FieldJson(5652, "STARLING"),
      new FieldJson(951, "STATFJORD [UK]"),
      new FieldJson(6682, "STATFJORD(CROSS BORDER)"),
      new FieldJson(6352, "STELLA"),
      new FieldJson(6452, "STILLINGFLEET COAL MINE VENT"),
      new FieldJson(1017, "STIRLING"),
      new FieldJson(1452, "STOCKBRIDGE"),
      new FieldJson(1661, "STORRINGTON"),
      new FieldJson(1393, "STRATHSPEY"),
      new FieldJson(6247, "SUTTON MANOR COAL MINE VENT"),
      new FieldJson(1087, "SYCAMORE"),
      new FieldJson(952, "TARTAN"),
      new FieldJson(1147, "TEAL"),
      new FieldJson(2057, "TEAL SOUTH"),
      new FieldJson(2046, "TELFORD"),
      new FieldJson(953, "TERN"),
      new FieldJson(5654, "TETHYS"),
      new FieldJson(954, "THAMES"),
      new FieldJson(1115, "THELMA"),
      new FieldJson(955, "THISTLE"),
      new FieldJson(1628, "THURNE"),
      new FieldJson(984, "TIFFANY"),
      new FieldJson(985, "TONI"),
      new FieldJson(5192, "TOPAZ"),
      new FieldJson(6212, "TORMORE"),
      new FieldJson(1170, "TRENT"),
      new FieldJson(4392, "TRUMFLEET"),
      new FieldJson(5312, "TULLICH"),
      new FieldJson(5492, "TWEEDSMUIR"),
      new FieldJson(5493, "TWEEDSMUIR SOUTH"),
      new FieldJson(3552, "TYNE NORTH"),
      new FieldJson(1801, "TYNE SOUTH"),
      new FieldJson(6675, "ULA"),
      new FieldJson(6677, "VALHALL"),
      new FieldJson(5452, "VALKYRIE"),
      new FieldJson(2751, "VAMPIRE"),
      new FieldJson(958, "VANGUARD"),
      new FieldJson(959, "VICTOR"),
      new FieldJson(6015, "VICTORIA"),
      new FieldJson(1365, "VIKING B [pt of VIKING GROUP]"),
      new FieldJson(2065, "VIKING C [pt of VIKING GROUP]"),
      new FieldJson(2064, "VIKING D [pt of VIKING GROUP]"),
      new FieldJson(2063, "VIKING E [pt of VIKING GROUP]"),
      new FieldJson(5313, "VISCOUNT"),
      new FieldJson(4992, "VIXEN"),
      new FieldJson(960, "VULCAN"),
      new FieldJson(1454, "WAREHAM"),
      new FieldJson(5952, "WARSOP MAIN COAL MINE VENT"),
      new FieldJson(3872, "WAVENEY"),
      new FieldJson(1642, "WELTON"),
      new FieldJson(1050, "WENLOCK"),
      new FieldJson(1019, "WENSUM [pt of THAMES COMPLEX]"),
      new FieldJson(1029, "WEST BRAE"),
      new FieldJson(1198, "WEST DON"),
      new FieldJson(1643, "WEST FIRSBY"),
      new FieldJson(963, "WEST SOLE"),
      new FieldJson(6243, "WHELDALE COAL MINE VENT"),
      new FieldJson(1644, "WHISBY"),
      new FieldJson(1415, "WHITTLE [pt of JUNO]"),
      new FieldJson(6244, "WHITWELL COAL MINE VENT"),
      new FieldJson(1079, "WINDERMERE"),
      new FieldJson(6274, "WINGATE"),
      new FieldJson(1053, "WISSEY"),
      new FieldJson(1054, "WOLLASTON [pt of JUNO]"),
      new FieldJson(4152, "WOOD"),
      new FieldJson(5494, "WREN"),
      new FieldJson(1456, "WYTCH FARM"),
      new FieldJson(964, "YARE [pt of THAMES COMPLEX]"),
      new FieldJson(2392, "YORK")
  );

}
