name: field-consents
services:
  postgres:
    image: postgres:14.3-alpine
    ports:
      - ":5432"
    environment:
      POSTGRES_DB: fcs
      POSTGRES_USER: fcs_app
      POSTGRES_PASSWORD: dev1