package uk.co.nstauthority.fieldconsents.application.caseprocessing.casestatusflag;

public enum CaseStatusFlag {
  // Application update
  APPLICATION_UPDATE_OPEN,
  APPLICATION_UPDATE_NOT_OPEN,
  APPLICATION_UPDATE_STARTED,
  IS_UPDATABLE,

  // Assignment
  CAM_ASSIGNED,
  CAM_NOT_ASSIGNED,
  CASE_OFFICER_ASSIGNED,
  CASE_OFFICER_NOT_ASSIGNED,

  // Case notes
  CASE_NOTES_ALLOWED,

  // Consent
  CONSENT_DATA_EXISTS,
  CONSENT_APPROVED_FOR_ISSUE,
  CONSENT_NOT_APPROVED_FOR_ISSUE,
  NON_EXPIRED_CONSENT_EXISTS,
  NON_WITHDRAWN_OR_DELETED_REVISION_APPLICATION_DOES_NOT_EXIST,

  // Revisions
  IS_REVISABLE,

  // Consultation
  CONSULTATION_OPEN,
  CONSULTATION_NOT_OPEN,
  CONSULTATION_FURTHER_INFORMATION_OPEN,
  CONSULTATION_FURTHER_INFORMATION_NOT_OPEN,

  // Mail merge
  MAIL_MERGE_ERROR_PRESENT,
  MAIL_MERGE_ERROR_NOT_PRESENT,

  // Technical review
  TECHNICAL_REVIEW_OPEN,
  TECHNICAL_REVIEW_NOT_OPEN,

  // Withdrawal
  WITHDRAWAL_OPEN,
  WITHDRAWAL_NOT_OPEN,
}
