package uk.co.nstauthority.fieldconsents.application.caseprocessing.casestatusflag;

public enum CaseStatusFlag {
  CASE_OFFICER_NOT_ASSIGNED,
  CASE_OFFICER_ASSIGNED,
  WITHDRAWAL_OPEN,
  NO_WITHDRAWAL_OPEN,
  TECHNICAL_REVIEW_OPEN,
  NO_TECHNICAL_REVIEW_OPEN,
  CASE_NOTES_ALLOWED,
  APPLICATION_UPDATE_OPEN,
  APPLICATION_UPDATE_STARTED,
  NO_APPLICATION_UPDATE_OPEN,
  CONSULTATION_OPEN,
  NO_CONSULTATION_OPEN,
  CONSULTATION_UNASSIGNED,
  CONSULTATION_FURTHER_INFORMATION_OPEN,
  NO_CONSULTATION_FURTHER_INFORMATION_OPEN,
  CAM_NOT_ASSIGNED,
  CAM_ASSIGNED
}
