CREATE USER fcs_migration IDENTIFIED BY "<password>"
DEFAULT TABLESPACE tbsdata
TEMPORARY TABLESPACE TEMP
PROFILE mgr_user
QUOTA UNLIMITED ON TBSBLOB
QUOTA UNLIMITED ON TBSCLOB
QUOTA UNLIMITED ON TBSDATA
QUOTA UNLIMITED ON TBSIDX;

GRANT CREATE SESSION TO fcs_migration;

GRANT SELECT ANY TABLE TO fcs_migration;

GRANT CREATE TABLE TO fcs_migration;

GRANT CREATE SEQUENCE TO fcs_migration;

GRANT CREATE VIEW TO fcs_migration;