package uk.co.nstauthority.fieldconsents.application.workareapriority;

public enum ApplicationWorkAreaPriorityReason {
  APPLICATION_CREATED,
  APPLICATION_SUBMITTED,
  UPDATE_SUBMITTED,
  OPERATOR_WITHDRAWAL_REQUEST,
  REGULATOR_REJECT_WITHDRAWAL_REQUEST,
  CASE_OFFICER_TAKE_OWNERSHIP,
  CASE_OFFICER_RELEASE_OWNERSHIP,
  CASE_OFFICER_ASSIGN_OWNERSHIP,
  TECHNICAL_REVIEW_REQUEST,
  TECHNICAL_REVIEWER_ASSIGN_OWNERSHIP,
  APPLICATION_UPDATE_REQUEST,
  CONSULTATION_REQUEST,
  CONSULTATION_RESPONDER_ASSIGNMENT,
  CONSULTATION_RESPONSE,
  CONSULTATION_FURTHER_INFORMATION_REQUESTED,
  CONSULTATION_FURTHER_INFORMATION_RESPONDED,
  CAM_ASSIGN_OWNERSHIP,
}
