package uk.co.nstauthority.fieldconsents.query;

import java.time.Instant;
import java.time.LocalDate;
import uk.co.nstauthority.fieldconsents.application.ApplicationType;
import uk.co.nstauthority.fieldconsents.application.ApplicationVersionStatus;
import uk.co.nstauthority.fieldconsents.application.caseprocessing.consultation.furtherinformation.FurtherInformationStatus;
import uk.co.nstauthority.fieldconsents.application.consentlength.ConsentLengthType;
import uk.co.nstauthority.fieldconsents.assets.AssetType;
import uk.co.nstauthority.fieldconsents.teams.permissionmanagement.regulator.RegulatorTeamRole;

public record ApplicationDataItemDto(
    Integer applicationId,
    Integer applicationVersionId,
    ApplicationType type,
    Integer variationNo,
    Integer applicationNo,
    Integer versionNo,
    Integer operatorId,
    ApplicationVersionStatus status,
    AssetType assetType,
    Integer assetId,
    String assetName,
    ConsentLengthType duration,
    Integer consentYear,
    LocalDate shortTermStartDate,
    LocalDate shortTermEndDate,
    Integer longTermStartYear,
    Integer longTermEndYear,
    Instant submittedDateTime,
    Long submittedByWuaId,
    Boolean aceFlag,
    Long caseOfficerWuaId,
    Long camWuaId,
    RegulatorTeamRole currentCaseOwner,
    Boolean withdrawalOpen,
    Long technicalReviewerWuaId,
    Boolean technicalReviewOpen,
    Instant technicalReviewDeadline,
    Boolean applicationUpdateOpen,
    Instant applicationUpdateDeadline,
    Boolean consultationOpen,
    Instant consultationDeadline,
    FurtherInformationStatus consultationFurtherInformationStatus,
    String licences,
    Boolean approvedForIssue,
    LocalDate consentStartDate,
    LocalDate consentEndDate,
    Boolean consentIssued
) {
}
