package uk.co.nstauthority.fieldconsents.application.bulkcaseactions.bulkissueconsents;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneId;
import java.util.List;
import java.util.stream.IntStream;
import net.javacrumbs.shedlock.core.LockAssert;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import uk.co.nstauthority.fieldconsents.application.ApplicationVersion;
import uk.co.nstauthority.fieldconsents.application.caseprocessing.consent.issuing.ConsentIssuingService;
import uk.co.nstauthority.fieldconsents.audit.AuditRevisionUtil;
import uk.co.nstauthority.fieldconsents.authentication.ServiceUserDetail;
import uk.co.nstauthority.fieldconsents.energyportal.WebUserAccountId;
import uk.co.nstauthority.fieldconsents.energyportal.user.EnergyPortalUserDto;
import uk.co.nstauthority.fieldconsents.energyportal.user.EnergyPortalUserDtoTestUtil;
import uk.co.nstauthority.fieldconsents.energyportal.user.EnergyPortalUserService;

@ExtendWith(MockitoExtension.class)
class BulkIssueConsentsServiceTest {

  private final Clock clock = Clock.fixed(Instant.now(), ZoneId.systemDefault());

  @Mock
  private BulkIssueConsentTaskRepository bulkIssueConsentTaskRepository;

  @Mock
  private BulkIssueConsentRunRepository bulkIssueConsentRunRepository;

  @Mock
  private EnergyPortalUserService energyPortalUserService;

  @Mock
  private ConsentIssuingService consentIssuingService;

  @Mock
  private BulkIssueConsentEmailService bulkIssueConsentEmailService;

  private BulkIssueConsentsService bulkIssueConsentsService;

  private EnergyPortalUserDto energyPortalUser;
  private ServiceUserDetail user;
  private Long userWuaId;
  private BulkIssueConsentRun bulkIssueConsentRun;

  @BeforeEach
  void setUp() {
    this.bulkIssueConsentsService = spy(new BulkIssueConsentsService(
        clock,
        bulkIssueConsentTaskRepository,
        bulkIssueConsentRunRepository,
        energyPortalUserService,
        consentIssuingService,
        bulkIssueConsentEmailService
    ));

    energyPortalUser = EnergyPortalUserDtoTestUtil.Builder().build();
    user = ServiceUserDetail.from(energyPortalUser);
    userWuaId = energyPortalUser.webUserAccountId();
    bulkIssueConsentRun = new BulkIssueConsentRun(userWuaId);
  }

  @Test
  void getConsentsPendingIssue() {
    var consentsPendingIssue = 10L;
    when(bulkIssueConsentTaskRepository.countAllByFinishedAtIsNull()).thenReturn(consentsPendingIssue);
    assertThat(bulkIssueConsentsService.getCountOfConsentsNotYetIssued()).isEqualTo(consentsPendingIssue);
  }

  @Test
  void queueApplicationsForConsentIssue() {
    var applicationVersions = IntStream.range(0, 10).mapToObj(i -> new ApplicationVersion()).toList();

    bulkIssueConsentsService.queueApplicationsForIssue(applicationVersions, user);

    @SuppressWarnings("unchecked")
    ArgumentCaptor<List<BulkIssueConsentsTask>> bulkIssueConsentTasksCaptor = ArgumentCaptor.forClass(List.class);
    verify(bulkIssueConsentTaskRepository).saveAll(bulkIssueConsentTasksCaptor.capture());

    var bulkIssueConsentTasks = bulkIssueConsentTasksCaptor.getValue();

    for (var i = 0; i < bulkIssueConsentTasks.size(); i++) {
      var bulkConsentIssueTask = bulkIssueConsentTasks.get(i);

      assertThat(bulkConsentIssueTask.getCreatedAt()).isEqualTo(clock.instant());
      assertThat(bulkConsentIssueTask.getApplicationVersion()).isEqualTo(applicationVersions.get(i));
      assertThat(bulkConsentIssueTask.getStartedAt()).isNull();
      assertThat(bulkConsentIssueTask.getFinishedAt()).isNull();
      assertThat(bulkConsentIssueTask.getErrorDetails()).isNull();
    }
  }

  @Test
  void bulkIssueConsents() {
    LockAssert.TestHelper.makeAllAssertsPass(true);
    var nonFinishedTasks = IntStream.range(0, 10).mapToObj(i -> new BulkIssueConsentsTask()).toList();

    when(energyPortalUserService.getServiceUserByWuaId(WebUserAccountId.from(userWuaId))).thenReturn(
        ServiceUserDetail.from(energyPortalUser));

    for (var nonFinishedTask : nonFinishedTasks) {
      nonFinishedTask.setBulkIssueConsentRun(bulkIssueConsentRun);
    }

    when(bulkIssueConsentTaskRepository.findAllByFinishedAtIsNull()).thenReturn(nonFinishedTasks);

    // Verify that the calls to issueConsent are wrapped in withFallbackAuditUser, so that the audit events generated by issuing
    // the consent are populated with the correct issuing user for the case history events.
    doAnswer(invocation -> {
      var user = invocation.getArgument(1);
      assertThat(AuditRevisionUtil.getFallbackAuditUser()).isEqualTo(user);
      return null;
    }).when(bulkIssueConsentsService).issueConsent(any(), any());

    bulkIssueConsentsService.bulkIssueConsents();

    for (var nonFinishedTask : nonFinishedTasks) {
      verify(bulkIssueConsentsService).issueConsent(nonFinishedTask, user);
    }
  }

  @Test
  void issueConsent() {
    var bulkIssueConsentTask = new BulkIssueConsentsTask();
    var applicationVersion = new ApplicationVersion();

    bulkIssueConsentTask.setBulkIssueConsentRun(bulkIssueConsentRun);
    bulkIssueConsentTask.setApplicationVersion(applicationVersion);

    bulkIssueConsentsService.issueConsent(bulkIssueConsentTask, user);

    verify(consentIssuingService).issueConsent(applicationVersion, user);

    var bulkIssueConsentTaskCaptor = ArgumentCaptor.forClass(BulkIssueConsentsTask.class);
    verify(bulkIssueConsentTaskRepository).save(bulkIssueConsentTaskCaptor.capture());
    assertThat(bulkIssueConsentTask)
        .extracting(
            BulkIssueConsentsTask::getStartedAt,
            BulkIssueConsentsTask::getFinishedAt,
            BulkIssueConsentsTask::getErrorDetails
        )
        .containsExactly(
            clock.instant(),
            clock.instant(),
            null
        );
  }

  @Test
  void issueConsent_exceptionWhenIssuingConsent() {
    var bulkIssueConsentTask = new BulkIssueConsentsTask();
    var applicationVersion = new ApplicationVersion();

    bulkIssueConsentTask.setBulkIssueConsentRun(bulkIssueConsentRun);
    bulkIssueConsentTask.setApplicationVersion(applicationVersion);

    doThrow(new RuntimeException("Error running bulk issue consent task")).when(consentIssuingService).issueConsent(
        applicationVersion, user);

    bulkIssueConsentsService.issueConsent(bulkIssueConsentTask, user);

    verify(consentIssuingService).issueConsent(applicationVersion, user);

    var bulkIssueConsentTaskCaptor = ArgumentCaptor.forClass(BulkIssueConsentsTask.class);
    verify(bulkIssueConsentTaskRepository).save(bulkIssueConsentTaskCaptor.capture());
    assertThat(bulkIssueConsentTask)
        .extracting(
            BulkIssueConsentsTask::getStartedAt,
            BulkIssueConsentsTask::getFinishedAt,
            BulkIssueConsentsTask::getErrorDetails
        )
        .containsExactly(
            clock.instant(),
            clock.instant(),
            "Error running bulk issue consent task"
        );
  }
}