package uk.co.nstauthority.fieldconsents.teams.permissionmanagement;

import java.util.EnumSet;
import java.util.Set;

public enum RolePermission {
  GRANT_ROLES,
  MANAGE_INDUSTRY_TEAMS,
  CREATE_FCS_APPLICATIONS,
  VIEW_FCS_APPLICATIONS,
  EDIT_FCS_APPLICATIONS,
  PAY_AND_SUBMIT_FCS_APPLICATIONS,
  VIEW_FCS_CONSENTS,
  PROCESS_FCS_APPLICATIONS,
  ASSIGN_FCS_APPLICATIONS,
  TECHNICAL_REVIEW_FCS_APPLICATIONS,
  VIEW_FCS_CASE_PROCESSING_DOCUMENTS,
  EDIT_FCS_CASE_PROCESSING_DOCUMENTS,
  ALLOCATE_CONSULTATION,
  RESPOND_TO_CONSULTATION,
  MANAGE_ASSETS,
  MANAGE_FEE_PERIODS,
  MANAGE_DOCUMENT_TEMPLATES,
  AUTHORISE_FCS_CONSENTS
  ;

  public static final Set<RolePermission> VIEW_PERMISSIONS =
      Set.of(RolePermission.VIEW_FCS_APPLICATIONS, RolePermission.VIEW_FCS_CONSENTS);

  public static final Set<RolePermission> REGULATOR_PERMISSIONS =
      EnumSet.of(
          RolePermission.PROCESS_FCS_APPLICATIONS,
          RolePermission.ASSIGN_FCS_APPLICATIONS,
          RolePermission.TECHNICAL_REVIEW_FCS_APPLICATIONS,
          RolePermission.AUTHORISE_FCS_CONSENTS
      );
}
